### ISSUE TITLE
Native addons

### ISSUE THREAD

**Issue by mcollina** [microsoft/node-v0.12#10]
Given most native addons use the V8 APIs, is there any plans from Microsoft to either contribute something to [nan](http://npm.im/nan), so that it allows addons to be compatible with Chakra, or some guidelines to port native modules?

Also #9 is relevant too at this point.

**Comment by nadavbar** [comment]
Since the way that this fork was made is by implementing a shim for the v8 APIs that uses Chakra under the hood, it should possible to compile existing native addons against this version of node without changing their code (since the APIs are the same)

**Comment by mcollina** [comment]
Oh great. That was not really clarified in the README, maybe it is worth adding?

**Comment by jianchun** [comment]
Thanks for the suggestion! Updated README. Hope it's clearer.
