### ISSUE TITLE
How do i set `Enable Experimental JavaScript features` ?

### ISSUE THREAD

**Issue by yosuke-furukawa** [microsoft/node-v0.12#11]
I would like to use ES6 features under flag like `--harmony` .
How do I set the flag??

**Comment by jianchun** [comment]
Currently the Chakra runtime hosting API ([JSRT](https://msdn.microsoft.com/en-us/library/dn249673%28v=vs.94%29.aspx)) does not support experimental feature flags. We have a backlog item to enable this in future.
