### ISSUE TITLE
Building issues 

### ISSUE THREAD

**Issue by sjkillen** [microsoft/node-v0.12#12]
Hello, I apologize if this isn't the right place to post this, But I've been trying to build this and I keep coming up with tons of errors

I have all the prerequisites except for Windows 10 tools, which this page said was included with VS 2015
https://dev.windows.com/en-us/downloads/windows-10-developer-tools

Most of the errors/warnings are about v8 files, could anyone point me in the right direction?

**Comment by jianchun** [comment]
@spleen387 Could you post some errors/warnings? We can help identify the cause.

VS 2015 indeed includes the tools. I'm not sure if the tools are installed by default though. You can try install the standalone SDK from your link (at bottom right of the page).

**Comment by sjkillen** [comment]
Here's one

```
D:\Visual Studio 2015\VC\include\xmemory0(942): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const v8::internal::zone_allocator<v8::internal::compiler::Node *>' (or there is no acceptable conversion) (compiling source file ..\..\src\compiler\graph-builder.cc) [C:\Users\Spencer\Documents\GitHub\node\deps\v8\tools\gyp\v8_base.vcxproj]
  C:\Users\Spencer\Documents\GitHub\node\deps\v8\src/zone-allocator.h(53): note: could be 'bool v8::internal::zone_allocator<v8::internal::compiler::Node *>::operator ==(const v8::internal::zone_allocator<v8::internal::compiler::Node *> &)' (compiling source file ..\..\src\compiler\graph-builder.cc)
  D:\Visual Studio 2015\VC\include\system_error(379): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept' (compiling source file ..\..\src\compiler\graph-builder.cc)
  D:\Visual Studio 2015\VC\include\system_error(371): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept' (compiling source file ..\..\src\compiler\graph-builder.cc)
  D:\Visual Studio 2015\VC\include\system_error(363): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept' (compiling source file ..\..\src\compiler\graph-builder.cc)
```

Thanks, I figured out I have the tools installed

Here's the full log http://pastebin.com/sqNCAuAs

**Comment by jianchun** [comment]
It looks you were running vcbuild.bat without “chakra” switch. That would build node with default V8 JavaScript engine. However the version of V8 seems not building with VS2015.

To build with chakra, run “vcbuild.bat chakra nosign” as shown in [README.md](https://github.com/Microsoft/node#how-to-build-with-chakra-on-windows).

Hope this helps. Please let us know if it works. Thanks!

**Comment by sjkillen** [comment]
Thanks it worked!
I feel silly, I was trying to figure out why it wouldn't build before when I didn't have the tools, So I was following https://github.com/joyent/node

Incase it helps anyone else I got the tools by checking the Universal Windows app development tools box in the VS install/modify,

Thanks a lot for your help!
