### ISSUE TITLE
Why wouldn't we just create a script to install applications ?

### ISSUE THREAD

**Issue by AlexisTM** [microsoft/node-v0.12#14]
Dear, 

Why wouldn't we just create a script called npm.cmd like in the legacy nodeJS and add it to the path ?

```
:: Created by npm, please don't edit manually.
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe" "%~dp0\.\node_modules\npm\bin\npm-cli.js" %*
) ELSE (
  node "%~dp0\.\node_modules\npm\bin\npm-cli.js" %*
)
```

With that kind of script, we will be able to use : 

> npm install package

**Comment by jianchun** [comment]
@AlexisTM Thank you for your feedback. Yes, that script already exists (in the source tree). But there are other problems to be solved. Firstly we need an installer to setup node.js/npm layout, and the installer must not conflict with existing node.js installation. Secondly we need a node-gyp solution to support existing native node.js addons. We are working to improve this experience.

**Comment by AlexisTM** [comment]
I though it was an oversight. My mistake!

The main problem of the WoA (Windows on ARM) system was to be compatible only with C++/C# from visual studio. With the new python/NodeJS support (Maybe Goland or ruby should go next) it became a great I/O board withtout having to configure everything in Linux! Great job! I will use it for my next project!
