### ISSUE TITLE
please implement FunctionTemplate::Inherit

### ISSUE THREAD

**Issue by mybios** [microsoft/node-v0.12#15]
We use FunctionTemplate::Inherit to export C++ complex class to javascript in our game engine . thanks

**Comment by jianchun** [comment]
Thanks for letting us know! We will address this.

**Comment by mybios** [comment]
I was create a PR https://github.com/Microsoft/node/pull/17 to do this. Please review.

**Comment by jianchun** [comment]
Thanks! PR #19 was accepted and merged.
