### ISSUE TITLE
Open Source Chakra / clear things up with whitelisted dll files

### ISSUE THREAD

**Issue by cookiengineer** [microsoft/node-v0.12#2]
Currently, this project lacks of major open source documentations and clarifications.

There's no hint that chakra will ever be open source, so that is kind of a hard issue.
Another issue is that Windows (at least IoT) uses explicitely whitelisted dlls, which may be required for other JIT compilers/runtimes.

Is there any way to use your own JIT in Win10?
I bet the community will deny a forced JIT (if it's not open source), as this is quality level of iOS. And to be honest, it can't get worse than that.

So, please clarify the usage of chakra here. It is nice to see API bindings for Chakra, but they won't have a real-world usecase if the JS engine can't be fixed and be maintained properly with the nodejs / iojs API and occuring bugs.

**Comment by aruneshchandra** [comment]
Thanks for your interest and feedback! We take all feedback seriously and evaluate our priorities based on what developers want. Open sourcing Chakra is often discussed within the team, but we don’t have anything to share at this point. Also, in Windows 10, apps with codeGeneration capability (https://msdn.microsoft.com/en-us/library/windows/apps/hh464936.aspx#general-use_capabilities) could dynamically generate code, thus providing the choice to developers. 

Let us know what further documentation and clarifications you’d like to see and we’ll add that to our backlog.

**Comment by chapgaga** [comment]
i think if you want to open source chakra, you should talk to ceo, discussion inside team is useless :(
@aruneshchandra
