### ISSUE TITLE
native addon compiling problem

### ISSUE THREAD

**Issue by dacolgit** [microsoft/node-v0.12#21]
Hello, I apologize if this isn't the right place to post this, but I've been trying to build the curve25519 addon  and I keep coming up with a lot of errors.
Most of the errors seem related to v8 files. Could you point me in the rigth direction? 

Here are the error I got:
![image](https://cloud.githubusercontent.com/assets/7942439/10486062/866d846e-728d-11e5-913c-4d7b8d52f9dd.png)

and here the code that doesn't compile:

![image](https://cloud.githubusercontent.com/assets/7942439/10486434/3b6bb524-728f-11e5-8b06-11a9c58227f8.png)

**Comment by nadavbar** [comment]
I think that some of the APIs that you are using have changed (The V8::Arguments class no longer exists in the new API), checkout the examples here: https://github.com/nodejs/node-v0.x-archive/blob/master/doc/api/addons.markdown

And you can also try and use NaN:https://github.com/nodejs/nan

**Comment by dacolgit** [comment]
Using NaN I'm now able to build the addons
Thanks
