### ISSUE TITLE
compiling error "node-v0.12\deps\chakrashim\include\v8.h(51): fatal error C1189: #error:  Wrong Windows SDK version"

### ISSUE THREAD

**Issue by qdk0901** [microsoft/node-v0.12#23]
I have build this code under windows 10 with newest update and vs2015 with update 1, and Node.js Tools for Windows IoT has been installed,  there is still a wrong sdk version error. I check the v8.h and find that the macro _CHAKRART_H_ has not been declared

**Comment by jianchun** [comment]
@qdk0901  It needs Windows 10 SDK (see https://github.com/Microsoft/node/issues/4).

However, we have moved our effort to latest Node.js and we have been working on v5/v6 (https://github.com/Microsoft/node). This v0.12 code is obsolete and has issues on latest Windows 10 update. Any reason you can't switch to latest?

**Comment by qdk0901** [comment]
@jianchun I didn't saw that latest version，I will try that version，many thanks.
