### ISSUE TITLE
patchTypedArrays issues in chakra_shim.

### ISSUE THREAD

**Issue by jdalton** [microsoft/node-v0.12#3]
I noticed some issues with [patchTypedArrays](https://github.com/Microsoft/node/blob/ch0.12.2/deps/chakrashim/lib/chakra_shim.js#L157-L229).

The additions are missing `toString` functions that mimic their original built-ins, e.g.
`function slice() { [native code] }`, and instead return their shim source.

This affects [lodash](https://www.npmjs.com/package/lodash)'s check to see whether `ArrayBuffer#slice` is built-in:

``` js
_.isNative(ArrayBuffer.prototype.slice);
// => false
```

I also noticed issues with the [overwritten](https://github.com/Microsoft/node/blob/ch0.12.2/deps/chakrashim/lib/chakra_shim.js#L217-L227) `TypedArray#set` method. It performs a `first instanceof Array` check which causes `set` not to work correctly when [passed a typed array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set).

I'm not sure why the methods are wrapped but they could hold a reference to their original method and defer to it when not needing the custom behavior. For example:

``` js
Float64Array.prototype.set = (function(func) {
  function set(array) {
    var offset = arguments[1];
    if (somethingToBranchFor) {
      /* do custom stuff */
    }
    return func.apply(this, arguments);
 }

 function toString() {
   return func.toString();
 }
 Object.defineProperty(set, 'toString', Object.getOwnPropertyDescriptor(func, 'toString')); 
 return set;
}(Float64Array.prototype.set));
```

**Comment by jianchun** [comment]
Thanks for the feedback! The patching seems not needed any more with latest Chakra native typed array support. We are removing it.

**Comment by jdalton** [comment]
Thanks!
