### ISSUE TITLE
vm module `runInNewContext` method causes fatal error.

### ISSUE THREAD

**Issue by jdalton** [microsoft/node-v0.12#4]
The lodash unit tests call `require('vm').runInNewContext(...);` which causes a fatal error:

> Assertion failed: false, file [src\jsrtcrosscontext.cc](https://github.com/Microsoft/node/blob/ch0.12.2/deps/chakrashim/src/jsrtcrosscontext.cc#L48), line 48.

I'm aware that support for the `vm` module isn't all there yet but I assumed it would just throw a JS error that I could catch.

**Comment by jdalton** [comment]
For now I'm checking the `process.jsEngine` name to bypass `vm` use.
See [lodash/lodash/test/test.js](https://github.com/lodash/lodash/blob/fcc09a7375bc52f1b483acf0e8151c220a9c5f22/test/test.js#L545-L547).

**Comment by jianchun** [comment]
I'm looking at vm issues and lodash. Will sync up with you. Thanks for feedback!

**Comment by jdalton** [comment]
Rock :rocket:!

**Comment by jianchun** [comment]
We have more fixes coming and lodash tests are passing.

**Comment by jdalton** [comment]
You all rock!
