### ISSUE TITLE
Clarify supported platforms for ChakraNode

### ISSUE THREAD

**Issue by jdalton** [microsoft/node-v0.12#5]
I've seen some confusion from devs related to the supported OSs for ChakraNode.
I think it comes down to the [readme](https://github.com/Microsoft/node/blob/ch0.12.2/README.md#to-build) having notes about `Unix/Macintosh`.

This could be resolved with a more explicit message about support.

**Comment by jianchun** [comment]
The readme is probably a temporary solution. We'll consider clearer message.
