### ISSUE TITLE
Support for serialport and Bluetooth Low Energy 

### ISSUE THREAD

**Issue by xmlking** [microsoft/node-v0.12#6]
Wonder if this node support  serialport and Bluetooth Low Energy  APIs on Windows 10? i.e Windows 10 on Raspberry Pi and PC?

**Comment by munyirik** [comment]
Hi xmlking, 
Support for serialport is not available yet. It does support Bluetooth LE API's. You can get them by using the "uwp" package (https://www.npmjs.com/package/uwp). The API's are under the Windows.Devices.Bluetooth.GenericAttributeProfile namespace.
Thanks.

**Comment by aruneshchandra** [comment]
Just to clarify - serialport works on latest builds of Windows 10 on PCs. However, at the moment there are some missing APIs in Windows 10 IoT core which runs on Raspberry Pi 2.
