### ISSUE TITLE
Memory issue?

### ISSUE THREAD

**Issue by obastemur** [microsoft/node-v0.12#8]
This is most probably an underlying engine (chakra) issue instead of the interface. Below code would end up showing out of memory error for V8(node/jxcore), works without a problem for SpiderMonkey(jxcore) and shows undefined behavior for chakra build.

```
jx / node.exe -pe "var arr=new Array(1e8); for(var i=0;i<1e8;i++) arr[i]=2 + (i%2); arr[1e6]"
```

produces `undefined` on ARM. If I check the value for arr[1e3], the result is 2 as expected. I would expect either `out of memory` error or showing the same result for both indexes.

Am I missing a point here ?

**Comment by jianchun** [comment]
We are still trying to reproduce this. We tried on ARM but got 2 as expected. Maybe we need a low memory device.

**Comment by obastemur** [comment]
I've tested this with Raspberry Pi 2 (which has 1 Gb - enough memory) Actually, in case of not enough memory I would expect an 'out of memory' error. 

What was the Windows build number ? Maybe there is an update ?

**Comment by jianchun** [comment]
Thanks for the info! Yes, we were looking at those 2 possibilities too. Had some difficulties to get our Pi 2 working. Will update this thread.
