### ISSUE TITLE
will chakra be open sourced?

### ISSUE THREAD

**Issue by chapgaga** [microsoft/node-v0.12#9]
haha

**Comment by ghost** [comment]
Microsoft, please either open source chakra, or change your outrageous terms to allow other javascript vms to run on windows arm. We will love you if you do.

**Comment by wonderdogone** [comment]
:+1:

**Comment by aruneshchandra** [comment]
Thanks for your interest and feedback! We take all feedback seriously and evaluate our priorities based on what developers want. Open sourcing Chakra is often discussed within the team, but we don’t have anything to share at this point. Also, in Windows 10, apps with codeGeneration capability (https://msdn.microsoft.com/en-us/library/windows/apps/hh464936.aspx#general-use_capabilities)could dynamically generate code, thus providing the choice to developers.

**Comment by aruneshchandra** [comment]
Please check my response on #2. I will go ahead and close this now.
